from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    MODERATOR = "MODERATOR"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BANNED = "BANNED"
    SUSPENDED = "SUSPENDED"


class MembershipStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class PaymentRequestStatus(StrEnum):
    AWAITING_PROOF = "AWAITING_PROOF"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    BANNED = "BANNED"


class ChatKind(StrEnum):
    CHANNEL = "CHANNEL"
    GROUP = "GROUP"
    SUPERGROUP = "SUPERGROUP"


class ProofKind(StrEnum):
    PHOTO = "PHOTO"
    DOCUMENT = "DOCUMENT"


class PaymentProvider(StrEnum):
    PAYPAL = "PAYPAL"
    BANK_TRANSFER = "BANK_TRANSFER"
    BINANCE = "BINANCE"
    STRIPE = "STRIPE"
    QR = "QR"
    CRYPTO = "CRYPTO"
    CUSTOM = "CUSTOM"


class LogAction(StrEnum):
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"
    USER_BANNED = "USER_BANNED"
    MEMBERSHIP_ACTIVATED = "MEMBERSHIP_ACTIVATED"
    MEMBERSHIP_EXPIRED = "MEMBERSHIP_EXPIRED"
    INVITE_LINK_CREATED = "INVITE_LINK_CREATED"
    USER_KICKED = "USER_KICKED"
    ADMIN_CREATED = "ADMIN_CREATED"
    ADMIN_REMOVED = "ADMIN_REMOVED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_UPDATED = "PLAN_UPDATED"
    CHAT_REGISTERED = "CHAT_REGISTERED"
    BACKUP_CREATED = "BACKUP_CREATED"
    ERROR = "ERROR"


class NotificationKind(StrEnum):
    PAYMENT_PENDING = "PAYMENT_PENDING"
    MEMBERSHIP_REMINDER_3D = "MEMBERSHIP_REMINDER_3D"
    MEMBERSHIP_REMINDER_1D = "MEMBERSHIP_REMINDER_1D"
    MEMBERSHIP_EXPIRED = "MEMBERSHIP_EXPIRED"

