from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    OWNER = "OWNER"
    SUPERVISOR = "SUPERVISOR"
    ADMIN = "ADMIN"
    MODERATOR = "MODERATOR"
    PAYMENTS = "PAYMENTS"
    SUPPORT = "SUPPORT"
    SALES = "SALES"
    READ_ONLY = "READ_ONLY"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BANNED = "BANNED"
    SUSPENDED = "SUSPENDED"


class MembershipStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REFUNDED = "REFUNDED"
    SUSPENDED = "SUSPENDED"


class PaymentRequestStatus(StrEnum):
    AWAITING_PROOF = "AWAITING_PROOF"
    INVOICE_CREATED = "INVOICE_CREATED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    BANNED = "BANNED"
    REFUNDED = "REFUNDED"
    SUSPECT = "SUSPECT"


class ChatKind(StrEnum):
    CHANNEL = "CHANNEL"
    GROUP = "GROUP"
    SUPERGROUP = "SUPERGROUP"


class ProofKind(StrEnum):
    PHOTO = "PHOTO"
    DOCUMENT = "DOCUMENT"


class PaymentProvider(StrEnum):
    PAYPAL = "PAYPAL"
    BANK_TRANSFER = "BANK_TRANSFER"
    TELEGRAM_STARS = "TELEGRAM_STARS"
    EXTERNAL_HOSTED_PAYMENT = "EXTERNAL_HOSTED_PAYMENT"
    BINANCE = "BINANCE"
    STRIPE = "STRIPE"
    QR = "QR"
    CRYPTO = "CRYPTO"
    CUSTOM = "CUSTOM"


class LogAction(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_STARTED = "PAYMENT_STARTED"
    PAYMENT_APPROVED = "PAYMENT_APPROVED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"
    PAYMENT_REFUNDED = "PAYMENT_REFUNDED"
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED"
    PAYMENT_RECEIPT_DUPLICATE = "PAYMENT_RECEIPT_DUPLICATE"
    USER_BANNED = "USER_BANNED"
    USER_REACTIVATED = "USER_REACTIVATED"
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    USER_CRM_STATUS_CHANGED = "USER_CRM_STATUS_CHANGED"
    MEMBERSHIP_ACTIVATED = "MEMBERSHIP_ACTIVATED"
    MEMBERSHIP_EXPIRED = "MEMBERSHIP_EXPIRED"
    MEMBERSHIP_EXTENDED = "MEMBERSHIP_EXTENDED"
    MEMBERSHIP_CANCELLED = "MEMBERSHIP_CANCELLED"
    MEMBERSHIP_SUSPENDED = "MEMBERSHIP_SUSPENDED"
    MEMBERSHIP_RESTORED = "MEMBERSHIP_RESTORED"
    MEMBERSHIP_RENEWAL_REQUESTED = "MEMBERSHIP_RENEWAL_REQUESTED"
    MEMBERSHIP_RENEWAL_APPROVED = "MEMBERSHIP_RENEWAL_APPROVED"
    MEMBERSHIP_RENEWAL_REJECTED = "MEMBERSHIP_RENEWAL_REJECTED"
    INVITE_LINK_CREATED = "INVITE_LINK_CREATED"
    INVITE_LINK_REVOKED = "INVITE_LINK_REVOKED"
    INVITE_LINK_REISSUED = "INVITE_LINK_REISSUED"
    INVITE_LINK_USED = "INVITE_LINK_USED"
    USER_JOINED_CHAT = "USER_JOINED_CHAT"
    USER_LEFT_CHAT = "USER_LEFT_CHAT"
    BROADCAST_CREATED = "BROADCAST_CREATED"
    BROADCAST_COMPLETED = "BROADCAST_COMPLETED"
    BROADCAST_PAUSED = "BROADCAST_PAUSED"
    BROADCAST_FAILED = "BROADCAST_FAILED"
    SUPPORT_MESSAGE = "SUPPORT_MESSAGE"
    SUPPORT_REPLY = "SUPPORT_REPLY"
    INBOX_ASSIGNED = "INBOX_ASSIGNED"
    INBOX_RESOLVED = "INBOX_RESOLVED"
    QUICK_REPLY_CREATED = "QUICK_REPLY_CREATED"
    QUICK_REPLY_UPDATED = "QUICK_REPLY_UPDATED"
    QUICK_REPLY_DELETED = "QUICK_REPLY_DELETED"
    DIRECT_MESSAGE_SENT = "DIRECT_MESSAGE_SENT"
    DIRECT_MESSAGE_FAILED = "DIRECT_MESSAGE_FAILED"
    CLIENTS_EXPORTED = "CLIENTS_EXPORTED"
    COUPON_REDEEMED = "COUPON_REDEEMED"
    REFERRAL_CREATED = "REFERRAL_CREATED"
    REFERRAL_REWARDED = "REFERRAL_REWARDED"
    FUNNEL_EVENT = "FUNNEL_EVENT"
    AUTOMATION_SCHEDULED = "AUTOMATION_SCHEDULED"
    AUTOMATION_EXECUTED = "AUTOMATION_EXECUTED"
    TELEGRAM_STARS_INVOICE_CREATED = "TELEGRAM_STARS_INVOICE_CREATED"
    TELEGRAM_STARS_PAYMENT_CONFIRMED = "TELEGRAM_STARS_PAYMENT_CONFIRMED"
    TELEGRAM_STARS_PAYMENT_REFUNDED = "TELEGRAM_STARS_PAYMENT_REFUNDED"
    USER_KICKED = "USER_KICKED"
    ADMIN_CREATED = "ADMIN_CREATED"
    ADMIN_REMOVED = "ADMIN_REMOVED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_UPDATED = "PLAN_UPDATED"
    CHAT_REGISTERED = "CHAT_REGISTERED"
    BACKUP_CREATED = "BACKUP_CREATED"
    ERROR = "ERROR"


class NotificationKind(StrEnum):
    PAYMENT_PENDING = "PAYMENT_PENDING"
    MEMBERSHIP_REMINDER_3D = "MEMBERSHIP_REMINDER_3D"
    MEMBERSHIP_REMINDER_1D = "MEMBERSHIP_REMINDER_1D"
    MEMBERSHIP_EXPIRED = "MEMBERSHIP_EXPIRED"


class AccessEventKind(StrEnum):
    JOIN = "JOIN"
    LEAVE = "LEAVE"
    KICK = "KICK"
    LINK_EXPIRED = "LINK_EXPIRED"


class CRMStatus(StrEnum):
    LEAD = "LEAD"
    INTERESTED = "INTERESTED"
    PLAN_VIEWED = "PLAN_VIEWED"
    PLAN_SELECTED = "PLAN_SELECTED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    RECEIPT_SUBMITTED = "RECEIPT_SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    RECOVERED = "RECOVERED"
    VIP = "VIP"
    BLOCKED = "BLOCKED"


class DeliveryStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class ReceiptStatus(StrEnum):
    CLEAN = "CLEAN"
    DUPLICATE = "DUPLICATE"
    SIMILAR = "SIMILAR"
    SUSPICIOUS = "SUSPICIOUS"


class CouponType(StrEnum):
    FIXED = "FIXED"
    PERCENTAGE = "PERCENTAGE"


class AutomationJobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
